import type { SkillLevel, TrackDefinition } from "@/types";

export const SKILL_TRACKS: Record<SkillLevel, TrackDefinition> = {
  foundation: {
    name: "Foundation",
    description: "Eliminate fillers, build awareness, find your speaking baseline",
    icon: "Target",
    color: "#16A34A",
    drills: [
      {
        id: "f1",
        type: "impromptu",
        name: "60-Second Clarity",
        description: "Speak for 60 seconds on a random topic with minimal filler words",
        durationSeconds: 60,
        level: "foundation",
        criteria: ["fillerControl >= 7"],
      },
      {
        id: "f2",
        type: "impromptu",
        name: "Slow & Steady",
        description: "Maintain a 120-140 WPM pace — conversational, not rushed",
        durationSeconds: 60,
        level: "foundation",
        criteria: ["wpm between 120-140"],
      },
      {
        id: "f3",
        type: "impromptu",
        name: "One Clear Point",
        description: "Make exactly one clear point in 60 seconds. No tangents.",
        durationSeconds: 60,
        level: "foundation",
        criteria: ["clarity >= 7"],
      },
      {
        id: "f4",
        type: "opening",
        name: "First Impression",
        description: "Deliver a confident opening line in 30 seconds",
        durationSeconds: 30,
        level: "foundation",
        criteria: ["confidence >= 6"],
      },
    ],
    unlockCriteria: null,
    levelUpCriteria: { minDrillsCompleted: 3, minAvgScore: 6 },
  },

  structure: {
    name: "Structure",
    description: "Master openings that hook, clean transitions, and strong closes",
    icon: "LayoutList",
    color: "#2563EB",
    drills: [
      {
        id: "s1",
        type: "impromptu",
        name: "The Hook",
        description: "Open with a hook that grabs attention in the first 10 seconds",
        durationSeconds: 60,
        level: "structure",
        criteria: ["engagement >= 7"],
      },
      {
        id: "s2",
        type: "impromptu",
        name: "Three-Point Framework",
        description: "Structure your speech with exactly 3 supporting points",
        durationSeconds: 60,
        level: "structure",
        criteria: ["structure >= 7"],
      },
      {
        id: "s3",
        type: "elevator",
        name: "Problem-Solution-Impact",
        description: "Pitch using a clear problem → solution → impact arc",
        durationSeconds: 90,
        level: "structure",
        criteria: ["structure >= 7", "clarity >= 7"],
      },
      {
        id: "s4",
        type: "opening",
        name: "The Callback Close",
        description: "End by tying back to your opening — full circle",
        durationSeconds: 60,
        level: "structure",
        criteria: ["structure >= 8"],
      },
    ],
    unlockCriteria: { requiredLevel: "foundation" },
    levelUpCriteria: { minDrillsCompleted: 3, minAvgScore: 7 },
  },

  storytelling: {
    name: "Storytelling",
    description: "Build narrative arcs, emotional beats, and vivid specificity",
    icon: "BookOpen",
    color: "#8B5CF6",
    drills: [
      {
        id: "st1",
        type: "impromptu",
        name: "The Personal Anecdote",
        description: "Tell a true personal story with a clear lesson in 60 seconds",
        durationSeconds: 60,
        level: "storytelling",
        criteria: ["engagement >= 7"],
      },
      {
        id: "st2",
        type: "impromptu",
        name: "Show, Don't Tell",
        description: "Describe a moment using sensory details — make us see, hear, and feel it",
        durationSeconds: 60,
        level: "storytelling",
        criteria: ["engagement >= 8"],
      },
      {
        id: "st3",
        type: "elevator",
        name: "The Customer Story",
        description: "Pitch through the lens of a customer's transformation",
        durationSeconds: 90,
        level: "storytelling",
        criteria: ["engagement >= 7", "structure >= 7"],
      },
      {
        id: "st4",
        type: "impromptu",
        name: "Emotional Contrast",
        description: "Take the audience from tension to resolution in 60 seconds",
        durationSeconds: 60,
        level: "storytelling",
        criteria: ["engagement >= 8", "confidence >= 7"],
      },
    ],
    unlockCriteria: { requiredLevel: "structure" },
    levelUpCriteria: { minDrillsCompleted: 3, minAvgScore: 7 },
  },

  presence: {
    name: "Presence",
    description: "Command silence, vary your vocal range, and control energy",
    icon: "Sparkles",
    color: "#E85D3A",
    drills: [
      {
        id: "p1",
        type: "impromptu",
        name: "The Dramatic Pause",
        description: "Use at least 2 deliberate pauses for emphasis in your speech",
        durationSeconds: 60,
        level: "presence",
        criteria: ["confidence >= 8"],
      },
      {
        id: "p2",
        type: "impromptu",
        name: "Vocal Range",
        description: "Vary your volume and pace — whisper, then project, then settle",
        durationSeconds: 60,
        level: "presence",
        criteria: ["engagement >= 8", "confidence >= 8"],
      },
      {
        id: "p3",
        type: "opening",
        name: "Command the Room",
        description: "Open with absolute authority. Make every word count.",
        durationSeconds: 30,
        level: "presence",
        criteria: ["confidence >= 9"],
      },
      {
        id: "p4",
        type: "qa",
        name: "Stay Composed",
        description: "Handle tough questions with calm authority",
        durationSeconds: 0,
        level: "presence",
        criteria: ["confidence >= 8"],
      },
    ],
    unlockCriteria: { requiredLevel: "storytelling" },
    levelUpCriteria: { minDrillsCompleted: 3, minAvgScore: 8 },
  },

  "world-class": {
    name: "World Class",
    description: "Thought leadership framing, adaptability, and reading the room",
    icon: "Crown",
    color: "#D97706",
    drills: [
      {
        id: "wc1",
        type: "impromptu",
        name: "Thought Leadership",
        description: "Present a contrarian perspective with conviction and data",
        durationSeconds: 60,
        level: "world-class",
        criteria: ["overall >= 8"],
      },
      {
        id: "wc2",
        type: "qa",
        name: "The Hot Seat",
        description: "Face 5 rounds of tough, skeptical questions without losing composure",
        durationSeconds: 0,
        level: "world-class",
        criteria: ["confidence >= 9", "clarity >= 8"],
      },
      {
        id: "wc3",
        type: "elevator",
        name: "The Vision Pitch",
        description: "Paint a compelling vision of the future that inspires action",
        durationSeconds: 90,
        level: "world-class",
        criteria: ["engagement >= 9", "confidence >= 8"],
      },
      {
        id: "wc4",
        type: "impromptu",
        name: "Pivot Master",
        description: "Start on one topic, get interrupted with a new topic mid-speech, and seamlessly pivot",
        durationSeconds: 60,
        level: "world-class",
        criteria: ["overall >= 9"],
      },
    ],
    unlockCriteria: { requiredLevel: "presence" },
    levelUpCriteria: { minDrillsCompleted: 4, minAvgScore: 8 },
  },
};

export const LEVEL_ORDER: SkillLevel[] = [
  "foundation",
  "structure",
  "storytelling",
  "presence",
  "world-class",
];

export function getNextLevel(current: SkillLevel): SkillLevel | null {
  const idx = LEVEL_ORDER.indexOf(current);
  if (idx === -1 || idx === LEVEL_ORDER.length - 1) return null;
  return LEVEL_ORDER[idx + 1];
}
